title: Matchlab
email: k.mikolajczyk@imperial.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Description for the site
baseurl: ""
url: "https://matchlab-imperial.github.io"
JEKYLL_ENV: "production"
address_1: "Room 1015, Department of Electrical and Electronic Engineering"
address_2: "Imperial College London"
address_3: "South Kensington Campus, London SW7 2AZ"
# site_logo: "/assets/images/logo1.png" # Site logo
github_url: "https://github.com/MatchLab-Imperial/Matchlab-Imperial.github.io"
facebook_url: 
instagram_url: 
youtube_url: 
twitter_url: 

# For jekyll-scholar plugin for Bibtex
collections:
  team:
    output: false
  research:
    output: true
  news:
    output: true
    

scholar:
  last_name: Mikolajczyk
  first_names: [Krystian, "K"]
  style: apa
  locale: en
  sort_by: [year, month]
  order: descending
  source: /_bibliography/
  bibliography: biblio.bib
  bibliography_template: biblio
  replace_strings: true
  join_strings: true
  query: "@*"


# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - assets/foundation/node_modules/
  - assets/foundation/src/
  - assets/foundation/.babelrc
  - assets/foundation/.gitignore
  - assets/foundation/config.yml
  - assets/foundation/gulpfile.babel.js
  - assets/foundation/package.json
  - assets/foundation/readme.md
  - assets/foundation/yarn.lock

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "single/research"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "single/news"
  
